### PR TITLE
Added raygun for production error reporting

### PR DESCRIPTION
**Pull request by sandlerben**

### CODE REVIEW

**Comment by sandlerben** [comment]
r @weronica 

How do we feel about adding this boilerplate to flask-base? @jondubin @aharelick It doesn't necessarily have to be raygun, but this seems like it ought to be standard.

**Comment by jondubin** [comment]
We should look into open sources solutions we can host ourselves

**Comment by sandlerben** [comment]
Any examples?

**Comment by jondubin** [comment]
[Errbit](https://github.com/errbit/errbit) seems to be a strong contender. I think investing in this sort of infrastructure for our projects is a good thing, but of course there's a tradeoff (paying with money vs paying with time).

**Comment by sandlerben** [comment]
I think we will stay within the free raygun plan for a long time so I'm not convinced we need to do a custom deployment yet

**Comment by jondubin** [comment]
Ahh, I didn't realize there was a free plan

**Comment by jondubin** [comment]
As far as I can tell the free Raygun plan only exists on Heroku, so this'll work as long as we stick with Heroku

**Comment by weronica** [comment]
LGTM

**Pull request merged**
